base_url = "https://chapeaux.github.io"
title = "Chapeaux"
description = "Web development tools for the many hats you wear."
default_language = "en"
compile_sass = false
build_search_index = false
generate_feeds = true
feed_filenames = ["atom.xml"]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
tagline = "A Digital Supply Chain for Web Assets"
github_org = "https://github.com/chapeaux"
logo = "/images/chapeaux_logo_aiux_2026.svg"
logo_wide = "/images/chapeaux_logo_wide_default_2026.svg"
logo_reverse = "/images/chapeaux_logo_aiux_reverse_2026.svg"
icon = "/images/chapeaux_icon_default_2026.svg"

[[extra.nav]]
name = "Contribute"
url = "/contribute/"

[[extra.nav]]
name = "Projects"
url = "/projects/"

[[extra.nav]]
name = "About"
url = "/about/"

[[extra.nav]]
name = "Blog"
url = "/blog/"

[[extra.nav]]
name = "Chapellerie"
url = "/chapellerie/"