[types]
"Blog Post" = "https://schema.org/BlogPosting"
"Web Page" = "https://schema.org/WebPage"
"Article" = "https://schema.org/Article"
"Organization" = "https://schema.org/Organization"

[properties]
title = "https://schema.org/name"
author = "https://schema.org/author"
date = "https://schema.org/datePublished"
description = "https://schema.org/description"
tags = "https://schema.org/keywords"
